install deps

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -26,7 +26,8 @@ jobs:
         run: which go
 
       # Runs a set of commands using the runners shell
-      # - name: Run a multi-line script
-      #   run: |
-      #     echo Add other actions to build,
-      #     echo test, and deploy your project.
+      - name: Run a multi-line script
+        run: |
+             go install github.com/magefile/mage@latest && mage -h >/dev/null 2>&1 || echo 'Failed to install mage'
+             wget -q https://github.com/defenseunicorns/zarf/releases/download/v0.29.2/zarf_v0.29.2_Linux_amd64 && chmod +x ./zarf_v0.29.2_Linux_amd64 && mv ./zarf_v0.29.2_Linux_amd64 $toolsPath/zarf && zarf -h >/dev/null 2>&1 || echo 'Failed to install zarf'
+             echo 'Install completed.'
